/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BillOperation {
    lineItems: Array<LineItem>;
    siteAddress: string;
    amountPaid: number;
    billDate: bigint;
    invoiceNumber: string;
    partyName: string;
    partyGstNo?: string;
}
export interface LineItem {
    rate: number;
    srNo: bigint;
    unit: string;
    hsnCode: string;
    productName: string;
    totalAmount: number;
    quantity: number;
}
export interface ProfitLossSummary {
    totalReceived: number;
    totalOutstanding: number;
    profitLossIndicator: boolean;
    totalBilled: number;
}
export interface Bill {
    lineItems: Array<LineItem>;
    finalAmount: number;
    cgst: number;
    sgst: number;
    siteAddress: string;
    totalGst: number;
    amountPaid: number;
    billDate: bigint;
    invoiceNumber: string;
    baseAmount: number;
    partyName: string;
    pendingAmount: number;
    roundOff: number;
    partyGstNo?: string;
}
export interface CompanySettings {
    ifscCode: string;
    bankName: string;
    gstin: string;
    panNumber: string;
    accountNumber: string;
    companyAddress: string;
}
export interface CompanyReport {
    totalReceived: number;
    totalServiceAmount: number;
    bills: Array<Bill>;
    totalPending: number;
}
export interface PartySummary {
    gstNumber: string;
    totalPaid: number;
    address: string;
    totalBilled: number;
    partyName: string;
    billCount: bigint;
    totalPending: number;
}
export interface UserProfile {
    name: string;
}
export interface PartyProfile {
    gstNumber: string;
    address: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBill(billOp: BillOperation): Promise<Bill>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    billExists(invoiceNumber: string): Promise<boolean>;
    deleteBill(invoiceNumber: string): Promise<Bill>;
    editBill(invoiceNumber: string, updatedBillOp: BillOperation): Promise<Bill>;
    getAggregate(): Promise<{
        totalGst: number;
        totalAmount: number;
    }>;
    getAllBills(): Promise<Array<Bill>>;
    getBill(invoiceNumber: string): Promise<Bill>;
    getBillsByParty(partyName: string): Promise<Array<Bill>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanyReport(partyName: string, from: bigint, to: bigint): Promise<CompanyReport>;
    getCompanySettings(): Promise<CompanySettings | null>;
    getPartyProfile(partyName: string): Promise<PartyProfile>;
    getPartySummary(): Promise<Array<PartySummary>>;
    getPartySummaryByDateRange(from: bigint, to: bigint): Promise<Array<PartySummary>>;
    getProfitLossSummary(from: bigint, to: bigint): Promise<ProfitLossSummary>;
    getUniquePartyNames(): Promise<Array<string>>;
    getUniqueProductNames(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCompanySettings(settings: CompanySettings): Promise<void>;
    savePartyAddress(partyName: string, address: string): Promise<void>;
    savePartyGstNumber(partyName: string, gstNumber: string): Promise<void>;
}
import type { Bill as _Bill, BillOperation as _BillOperation, CompanyReport as _CompanyReport, CompanySettings as _CompanySettings, LineItem as _LineItem, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBill(arg0: BillOperation): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.addBill(to_candid_BillOperation_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Bill_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBill(to_candid_BillOperation_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Bill_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async billExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.billExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.billExists(arg0);
            return result;
        }
    }
    async deleteBill(arg0: string): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0);
                return from_candid_Bill_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0);
            return from_candid_Bill_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async editBill(arg0: string, arg1: BillOperation): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.editBill(arg0, to_candid_BillOperation_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Bill_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBill(arg0, to_candid_BillOperation_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Bill_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAggregate(): Promise<{
        totalGst: number;
        totalAmount: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAggregate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAggregate();
            return result;
        }
    }
    async getAllBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBill(arg0: string): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return from_candid_Bill_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return from_candid_Bill_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillsByParty(arg0: string): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillsByParty(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillsByParty(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyReport(arg0: string, arg1: bigint, arg2: bigint): Promise<CompanyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyReport(arg0, arg1, arg2);
                return from_candid_CompanyReport_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyReport(arg0, arg1, arg2);
            return from_candid_CompanyReport_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanySettings(): Promise<CompanySettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanySettings();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanySettings();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartyProfile(arg0: string): Promise<PartyProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartyProfile(arg0);
            return result;
        }
    }
    async getPartySummary(): Promise<Array<PartySummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartySummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartySummary();
            return result;
        }
    }
    async getPartySummaryByDateRange(arg0: bigint, arg1: bigint): Promise<Array<PartySummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartySummaryByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartySummaryByDateRange(arg0, arg1);
            return result;
        }
    }
    async getProfitLossSummary(arg0: bigint, arg1: bigint): Promise<ProfitLossSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitLossSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitLossSummary(arg0, arg1);
            return result;
        }
    }
    async getUniquePartyNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniquePartyNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniquePartyNames();
            return result;
        }
    }
    async getUniqueProductNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueProductNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueProductNames();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCompanySettings(arg0: CompanySettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCompanySettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCompanySettings(arg0);
            return result;
        }
    }
    async savePartyAddress(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePartyAddress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePartyAddress(arg0, arg1);
            return result;
        }
    }
    async savePartyGstNumber(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePartyGstNumber(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePartyGstNumber(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Bill_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_CompanyReport_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanyReport): CompanyReport {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanySettings]): CompanySettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalReceived: number;
    totalServiceAmount: number;
    bills: Array<_Bill>;
    totalPending: number;
}): {
    totalReceived: number;
    totalServiceAmount: number;
    bills: Array<Bill>;
    totalPending: number;
} {
    return {
        totalReceived: value.totalReceived,
        totalServiceAmount: value.totalServiceAmount,
        bills: from_candid_vec_n8(_uploadFile, _downloadFile, value.bills),
        totalPending: value.totalPending
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineItems: Array<_LineItem>;
    finalAmount: number;
    cgst: number;
    sgst: number;
    siteAddress: string;
    totalGst: number;
    amountPaid: number;
    billDate: bigint;
    invoiceNumber: string;
    baseAmount: number;
    partyName: string;
    pendingAmount: number;
    roundOff: number;
    partyGstNo: [] | [string];
}): {
    lineItems: Array<LineItem>;
    finalAmount: number;
    cgst: number;
    sgst: number;
    siteAddress: string;
    totalGst: number;
    amountPaid: number;
    billDate: bigint;
    invoiceNumber: string;
    baseAmount: number;
    partyName: string;
    pendingAmount: number;
    roundOff: number;
    partyGstNo?: string;
} {
    return {
        lineItems: value.lineItems,
        finalAmount: value.finalAmount,
        cgst: value.cgst,
        sgst: value.sgst,
        siteAddress: value.siteAddress,
        totalGst: value.totalGst,
        amountPaid: value.amountPaid,
        billDate: value.billDate,
        invoiceNumber: value.invoiceNumber,
        baseAmount: value.baseAmount,
        partyName: value.partyName,
        pendingAmount: value.pendingAmount,
        roundOff: value.roundOff,
        partyGstNo: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.partyGstNo))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n3(_uploadFile, _downloadFile, x));
}
function to_candid_BillOperation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillOperation): _BillOperation {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineItems: Array<LineItem>;
    siteAddress: string;
    amountPaid: number;
    billDate: bigint;
    invoiceNumber: string;
    partyName: string;
    partyGstNo?: string;
}): {
    lineItems: Array<_LineItem>;
    siteAddress: string;
    amountPaid: number;
    billDate: bigint;
    invoiceNumber: string;
    partyName: string;
    partyGstNo: [] | [string];
} {
    return {
        lineItems: value.lineItems,
        siteAddress: value.siteAddress,
        amountPaid: value.amountPaid,
        billDate: value.billDate,
        invoiceNumber: value.invoiceNumber,
        partyName: value.partyName,
        partyGstNo: value.partyGstNo ? candid_some(value.partyGstNo) : candid_none()
    };
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
