/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LineItem = IDL.Record({
  'srNo' : IDL.Nat,
  'hsnCode' : IDL.Text,
  'productName' : IDL.Text,
  'amount' : IDL.Float64,
  'itemGst' : IDL.Float64,
});
export const Bill = IDL.Record({
  'lineItems' : IDL.Vec(LineItem),
  'finalAmount' : IDL.Float64,
  'cgst' : IDL.Float64,
  'sgst' : IDL.Float64,
  'totalGst' : IDL.Float64,
  'invoiceNumber' : IDL.Text,
  'baseAmount' : IDL.Float64,
  'partyName' : IDL.Text,
  'roundOff' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBill' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(LineItem)], [Bill], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAggregate' : IDL.Func(
      [],
      [IDL.Record({ 'totalGst' : IDL.Float64, 'totalAmount' : IDL.Float64 })],
      ['query'],
    ),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getBill' : IDL.Func([IDL.Text], [Bill], ['query']),
  'getBillsByParty' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LineItem = IDL.Record({
    'srNo' : IDL.Nat,
    'hsnCode' : IDL.Text,
    'productName' : IDL.Text,
    'amount' : IDL.Float64,
    'itemGst' : IDL.Float64,
  });
  const Bill = IDL.Record({
    'lineItems' : IDL.Vec(LineItem),
    'finalAmount' : IDL.Float64,
    'cgst' : IDL.Float64,
    'sgst' : IDL.Float64,
    'totalGst' : IDL.Float64,
    'invoiceNumber' : IDL.Text,
    'baseAmount' : IDL.Float64,
    'partyName' : IDL.Text,
    'roundOff' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBill' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(LineItem)], [Bill], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAggregate' : IDL.Func(
        [],
        [IDL.Record({ 'totalGst' : IDL.Float64, 'totalAmount' : IDL.Float64 })],
        ['query'],
      ),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getBill' : IDL.Func([IDL.Text], [Bill], ['query']),
    'getBillsByParty' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };