/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'lineItems' : Array<LineItem>,
  'finalAmount' : number,
  'cgst' : number,
  'sgst' : number,
  'totalGst' : number,
  'invoiceNumber' : string,
  'baseAmount' : number,
  'partyName' : string,
  'roundOff' : number,
}
export interface LineItem {
  'srNo' : bigint,
  'hsnCode' : string,
  'productName' : string,
  'amount' : number,
  'itemGst' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBill' : ActorMethod<[string, string, Array<LineItem>], Bill>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAggregate' : ActorMethod<
    [],
    { 'totalGst' : number, 'totalAmount' : number }
  >,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getBill' : ActorMethod<[string], Bill>,
  'getBillsByParty' : ActorMethod<[string], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];