/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'lineItems' : Array<LineItem>,
  'finalAmount' : number,
  'cgst' : number,
  'sgst' : number,
  'totalGst' : number,
  'amountPaid' : number,
  'billDate' : bigint,
  'invoiceNumber' : string,
  'baseAmount' : number,
  'partyName' : string,
  'pendingAmount' : number,
  'roundOff' : number,
}
export interface BillOperation {
  'lineItems' : Array<LineItem>,
  'billDate' : bigint,
  'invoiceNumber' : string,
  'partyName' : string,
}
export interface CompanyReport {
  'totalReceived' : number,
  'totalServiceAmount' : number,
  'bills' : Array<Bill>,
  'totalPending' : number,
}
export interface LineItem {
  'rate' : number,
  'srNo' : bigint,
  'unit' : string,
  'hsnCode' : string,
  'productName' : string,
  'totalAmount' : number,
  'quantity' : number,
}
export interface PartySummary {
  'gstNumber' : string,
  'totalPaid' : number,
  'totalBilled' : number,
  'partyName' : string,
  'billCount' : bigint,
  'totalPending' : number,
}
export interface ProfitLossSummary {
  'totalReceived' : number,
  'totalOutstanding' : number,
  'profitLossIndicator' : boolean,
  'totalBilled' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBill' : ActorMethod<[BillOperation], Bill>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'billExists' : ActorMethod<[string], boolean>,
  'deleteBill' : ActorMethod<[string], Bill>,
  'editBill' : ActorMethod<[string, BillOperation], Bill>,
  'getAggregate' : ActorMethod<
    [],
    { 'totalGst' : number, 'totalAmount' : number }
  >,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getBill' : ActorMethod<[string], Bill>,
  'getBillsByParty' : ActorMethod<[string], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyReport' : ActorMethod<[string, bigint, bigint], CompanyReport>,
  'getPartyGstNumber' : ActorMethod<[string], string>,
  'getPartySummary' : ActorMethod<[], Array<PartySummary>>,
  'getPartySummaryByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<PartySummary>
  >,
  'getProfitLossSummary' : ActorMethod<[bigint, bigint], ProfitLossSummary>,
  'getUniquePartyNames' : ActorMethod<[], Array<string>>,
  'getUniqueProductNames' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePartyGstNumber' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];